#!/bin/bash

if [[ ! -e /var/log/n8n-install.log ]]; then
    touch /var/log/n8n-install.log
fi

logfile=/var/log/n8n-install.log

if [[ ! -e /root/.npm ]]; then
    mkdir -p /root/.npm
fi

# Deals with errors
error_exit()
{
    echo "${1:-"Unknown Error"}" 1>&2
    echo "Last 10 entried by this script:"
    tail $logfile
    echo "Full log details are recorded in $logfile"
    exit 1
}

# Create log headings
log_heading()
{
    length=${#1}
    length=`expr $length + 8`
    printf '%*s' $length | tr ' ' '*'>>$logfile
    echo>>$logfile
    echo "*** $1 ***">>$logfile
    printf '%*s' $length | tr ' ' '*'>>$logfile
    echo>>$logfile
    echo $1...

}

clear

# 1. Install dependencies
log_heading "Installing dependencies"
apt install build-essential python -y &>>$logfile || error_exit "$LINENO: Unable to install dependencies" 
    
#Ajuste de permissões
#chown -R root:root "/root/.npm"
    
# 2. Add NodeJS 14.x Source List
log_heading "Add NodeJS 14.x Source List"
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - &>>$logfile || error_exit "$LINENO: Unable to update NodeJs source list"

# 3. Install Node JS
log_heading "Installing NodeJS 14.x"
apt install -y nodejs &>>$logfile || error_exit "$LINENO: Unable to install NodeJS"

log_heading "Install extra packages"
npm install -g node-gyp &>>$logfile
npm install @fortawesome/fontawesome-svg-core@1.x &>>$logfile
npm install @fortawesome/free-solid-svg-icons@5.x &>>$logfile
npm install @fortawesome/vue-fontawesome &>>$logfile
npm install fsevents@2.3.2 &>>$logfile
npm install -f &>>$logfile
npm install ssh2 &>>$logfile
npm config set user root install cpu-features &>>$logfile

# 4. Install n8n
log_heading "Installing n8n"
cd ~ &>>$logfile || error_exit "$LINENO: Unable to change working directory to home directory"
npm config set prefix ~/.nodejs_global &>>$logfile || error_exit "$LINENO: Unable to set the npm prefix to ~/.nodejs_global"
echo 'export PATH=~/.nodejs_global/bin:$PATH' | tee --append ~/.profile &>>$logfile || error_exit "$LINENO: Unable to update ~/.profile to update PATH variable"
source ~/.profile &>>$logfile || error_exit "$LINENO: Unable to reload ~/.profile "
npm install n8n -g &>>$logfile || error_exit "$LINENO: Unable to install n8n"

# 5. Install & Configure PM2
log_heading "Install & Configure PM2"
cd ~ &>>$logfile || error_exit "$LINENO: Unable to move the the home directory"
npm install pm2@latest -g &>>$logfile || error_exit "$LINENO: Unable to install PM2"
pm2 start n8n &>>$logfile || error_exit "$LINENO: Unable to start n8n using PM2"

# Install Complete (The second URL that is used needs to display the hostname dynamically)
IPADDR=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
message="The final phase of the installation has finished. You should be able to access the n8n WebUI from http://${IPADDR}:5678"
log_heading "${message}"
log_heading "Install Complete"
